#!/usr/bin/bash

start(){
	echo -e "\nThis is the dotfiles setup script.\nContinue? (y/n)"
	old_stty_cfg=$(stty -g)
	stty raw -echo
	answer=$( while ! head -c 1 | grep -i '[ny]' ;do true ;done )
	stty $old_stty_cfg
	if echo "$answer" | grep -iq "^y" ;then
		echo
	else
		echo "Quitting, setup aborted."
		exit 0
	fi
}

check_install() {
	if ! [ -x "$(command -v $1)" ]; then
		echo "[+] $1 is not installed, installing.."
		sudo apt-get install $1 -y
	else
		echo "[-] $1 is already installed, skipping.."
	fi
}


clear
echo -e "\n\n\t----- Setup dotfiles -----"

# 1. confirm setup
start

# 2. install programs
echo -e "\nChecking/Installing: vim, tmux, zsh, fzf, xclip\n"
check_install vim
check_install tmux
check_install zsh
check_install fzf
check_install xclip

# 3. switch to zsh
echo -e "\nChanging default shell to zsh.."
chsh -s $(which zsh)

# 4. backup old dotfiles
#echo -e "\nBacking up old dotfiles.."
# mv ~/.zshrc ~/.zshrc.old
# mv ~/.tmux.conf ~/.tmux.conf.old
# mv ~/.vimrc ~/.vimrc.old

# 5. setup new source files
echo -e "\nSetting up new dotfiles source.."
echo "source '$HOME/dotfiles/zsh/zshrc_manager.sh'" > ~/.zshrc
echo "so $HOME/dotfiles/vim/vimrc.vim" > ~/.vimrc
echo "source-file $HOME/dotfiles/tmux/tmux.conf" > ~/.tmux.conf
echo "[ -f $HOME/dotfiles/fzf/fzf.zsh ] && source $HOME/dotfiles/fzf/fzf.zsh" >> ~/.zshrc

echo -e "\n\nInstallation successful.\nPlease log-out and log-in to complete the setup.\n"
